# Needs the 'echoe' gem
require 'echoe'

Echoe.new('smartcard') do |p|
  p.project = 'smartcard' # rubyforge project
  
  p.author = 'Victor Costan'
  p.email = 'victor@costan.us'
  p.summary = 'Interface with ISO 7816 smart cards.'
  p.url = 'http://www.costan.us/smartcard'
  
  p.need_tar_gz = false
  p.clean_pattern += ['ext/**/*.manifest', 'ext/**/*_autogen.h']
  
  p.eval = proc do |p|
    case RUBY_PLATFORM
    when /mswin/
      p.files += ['lib/smartcard/pcsc.so']
      p.platform = Gem::Platform::WIN32

      # take out the extension info from the gemspec
      task :postcompile_hacks => [:compile] do
        p.extensions.clear
      end

      task :package => [ :clean, :compile, :postcompile_hacks ]
    end
  end
end